In [22]:
import numpy as np

#Creación de arrays numpy

a = np.array([1,2,3.4,5])
b = np.array([[1,2,3.5],[4,3,23]])

#Número de dimensiones
print(a.ndim)

#Forma
print(a.shape)
#Tamaño
print(a.size)
#Tipo
print(a.dtype)
#Tamaño
print(a.itemsize)


np.ones(2,dtype=None, order='C', like=None)

np.zeros(2,dtype=None, order='C', like=None)

#empty, arrange, linspace -> otros ejemplos

np.ones((2,8))


np.arange(2, 20, 3)

m1 = np.array([[1,2,4],[1,2,4]])
m2 = np.array([[1,2,4],[1,2,4]])

m3 = m1 + m2

print(m3)

print(m1*m2)

#Producto de matrices
# m1 @ m3

#m1 > 3 -> Devuelve arrays de booleanos

np.sqrt(1)

#Buscar max por eje
m1.max(axis=0)

#Buscar min por eje
m1.min(axis=1)

#Cambiar la forma de un array
m4 = np.arange(16)

print("16 elementos: \n", m4)
m4[0] = 10

print(m4)

1
(4,)
4
float64
8
[[2 4 8]
 [2 4 8]]
[[ 1  4 16]
 [ 1  4 16]]
16 elementos: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
